# Generated by Django 3.1.7 on 2021-03-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdegerler',
            name='yasin_ilk',
            field=models.SmallIntegerField(default=1, verbose_name='Başlangıç'),
        ),
        migrations.AddField(
            model_name='defaultdegerler',
            name='yasin_son',
            field=models.SmallIntegerField(default=6, verbose_name='Bitiş'),
        ),
    ]
