# Generated by Django 3.0 on 2021-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0003_auto_20210323_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='siyer',
            name='sayfa',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
