# Generated by Django 3.1.7 on 2021-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0004_siyer_sayfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultdegerler',
            name='ilmihal_ilk',
            field=models.SmallIntegerField(blank=True, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='ilmihal_son',
            field=models.SmallIntegerField(blank=True, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='kk_sayfa_ilk',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='kk_sayfa_son',
            field=models.SmallIntegerField(blank=True, default=604, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='yasin_ilk',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='yasin_son',
            field=models.SmallIntegerField(blank=True, default=6, verbose_name='Bitiş'),
        ),
    ]
