# Generated by Django 3.1.7 on 2021-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0006_auto_20210325_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultdegerler',
            name='yasin_ilk',
        ),
        migrations.RemoveField(
            model_name='defaultdegerler',
            name='yasin_son',
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='ilmihal_ilk',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='ilmihal_son',
            field=models.SmallIntegerField(blank=True, default=100, verbose_name='Bitiş'),
        ),
    ]
