# Generated by Django 3.1.7 on 2021-03-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0008_yasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NebeSuresi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YasinSuresi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='yasin',
            new_name='MulkSuresi',
        ),
        migrations.CreateModel(
            name='s_Yasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
                ('yasin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.yasinsuresi')),
            ],
        ),
    ]
