# Generated by Django 3.1.7 on 2021-03-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0009_auto_20210326_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_Nebe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Nebe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.nebesuresi')),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
            ],
        ),
        migrations.CreateModel(
            name='s_Mulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Mulk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.mulksuresi')),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
            ],
        ),
    ]
