# Generated by Django 3.1.7 on 2021-03-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0010_s_mulk_s_nebe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanicilar',
            name='session',
        ),
    ]
