# Generated by Django 3.1.7 on 2021-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0013_auto_20210331_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='siyer',
            new_name='SiyeriNebi',
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='AlakSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Alak Suresi'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='BeyyineSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Beyyine Suresi'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='DuhaSuresininAlti',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="Duha Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='FilSuresininAlti',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="Fil Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='IlmihalIlk',
            field=models.SmallIntegerField(blank=True, verbose_name='İlmihal Başlangıç Sayfası'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='IlmihalSon',
            field=models.SmallIntegerField(blank=True, verbose_name='İlmihal Bitiş Sayfası'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='KURANIKERIM',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="KUR'AN-I KERİM"),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='KURANIKERIMSayfaIlk',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name="KUR'AN-I KERİM Başlangıç Sayfası"),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='KURANIKERIMSayfaSon',
            field=models.SmallIntegerField(blank=True, default=604, verbose_name="KUR'AN-I KERİM Bitiş Sayfası"),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='MulkSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Mülk Suresi'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='NebeSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Nebe Suresi'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='PratikArapca',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Pratik Arapça'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='SiyeriNebi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Siyer-i Nebi'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='Tecvid',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Tecvid'),
        ),
        migrations.AlterField(
            model_name='defaultdegerler',
            name='YasinSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Yasin Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='AlakSuresi',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Alak Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='BeyyineSuresi',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Beyyine Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='DuhaSuresininAlti',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name="Duha Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='FilSuresininAlti',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name="Fil Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='IlmihalIlk',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='İlmihal Başlangıç Sayfası'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='IlmihalSon',
            field=models.SmallIntegerField(blank=True, default=100, null=True, verbose_name='İlmihal Bitiş Sayfası'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='KURANIKERIMSayfaIlk',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name="KUR'AN-I KERİM Başlangıç Sayfası"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='KURANIKERIMSayfaSon',
            field=models.SmallIntegerField(blank=True, default=600, null=True, verbose_name="KUR'AN-I KERİM Bitiş Sayfası"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='MulkSuresi',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Mülk Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='NebeSuresi',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Nebe Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='PratikArapca',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Pratik Arapça'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='SiyeriNebi',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Siyer-i Nebi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='Tecvid',
            field=models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True, verbose_name='Tecvid'),
        ),
    ]
