# Generated by Django 3.1.7 on 2021-04-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0016_alaksuresi_beyyinesuresi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeyyineSuresi',
            new_name='AlakBeyyineSuresi',
        ),
        migrations.DeleteModel(
            name='AlakSuresi',
        ),
    ]
