# Generated by Django 3.1.7 on 2021-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0022_defaultdegerler_bastanalasuresiarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlaSuresiLeylSuresiArasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('sure_isim', models.CharField(blank=True, max_length=150)),
                ('ayet_no', models.SmallIntegerField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='defaultdegerler',
            name='AlaSuresiLeylSuresiArasi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="A'la Suresi Leyl Suresi Arası Sureler"),
        ),
    ]
