# Generated by Django 3.1.7 on 2021-04-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0023_auto_20210402_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dualar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='defaultdegerler',
            name='Dualar',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Dualar'),
        ),
    ]
