# Generated by Django 3.1.7 on 2021-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0024_auto_20210402_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdegerler',
            name='Ilmihal',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='İlmihal'),
        ),
    ]
