# Generated by Django 3.1.7 on 2021-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0025_defaultdegerler_ilmihal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicilar',
            name='AlaSuresiLeylSuresiArasi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="A'la Suresi Leyl Suresi Arası Sureler"),
        ),
        migrations.AddField(
            model_name='kullanicilar',
            name='BastanAlaSuresiArasi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="Baştan A'la Suresine Kadar Olan Sureler"),
        ),
        migrations.AddField(
            model_name='kullanicilar',
            name='Dualar',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Dualar'),
        ),
        migrations.AddField(
            model_name='kullanicilar',
            name='Ilmihal',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='İlmihal'),
        ),
        migrations.AddField(
            model_name='kullanicilar',
            name='KURANIKERIM',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="KUR'AN-I KERİM"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='AlakBeyyineSureleri',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Alak-Beyyine Sureleri'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='DuhaSuresininAlti',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="Duha Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='FilSuresininAlti',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name="Fil Suresi'nin Altındaki Sureler"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='IlmihalIlk',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='İlmihal Başlangıç Sayfası'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='IlmihalSon',
            field=models.SmallIntegerField(blank=True, default=248, verbose_name='İlmihal Bitiş Sayfası'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='KURANIKERIMSayfaIlk',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name="KUR'AN-I KERİM Başlangıç Sayfası"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='KURANIKERIMSayfaSon',
            field=models.SmallIntegerField(blank=True, default=600, verbose_name="KUR'AN-I KERİM Bitiş Sayfası"),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='MulkSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Mülk Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='NebeSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Nebe Suresi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='PratikArapca',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Pratik Arapça'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='SiyeriNebi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Siyer-i Nebi'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='Tecvid',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Tecvid'),
        ),
        migrations.AlterField(
            model_name='kullanicilar',
            name='YasinSuresi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, verbose_name='Yasin Suresi'),
        ),
    ]
